server:
  port: 3031

spring:
  application:
    name: welfare-center

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
<<<<<<< HEAD
      #defaultZone: http://172.24.132.96:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
=======
      defaultZone: http://172.24.132.96:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/

>>>>>>> refs/heads/master
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true

