server:
  port: 2015


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml


spring:
  application:
    name: user-center
  redis:
    host: 39.104.97.83
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.104.97.83:3306/Pension?useUnicode=true&characterEncoding=utf8
    username: kedi
    password: kedi123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
  servlet:
    multipart:
      max-file-size: 5MB

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://172.24.132.96:8761/eureka/
      #defaultZone: http://192.168.23.147:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
     lease-renewal-interval-in-seconds: 5
     lease-expiration-duration-in-seconds: 10
     instanceId: ${spring.application.name}:${server.port}
     preferIpAddress: true

logging:
  level:
    com.kedi.usercenter.mapper: debug