server:
  port: 2011

spring:
  application:
    name: product-center

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.23.147:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true


feign:
  httpclient:
    connection-timeout: 20000
