server:
  port: 6010
spring:
  application:
    name: aliyun-duanxin
  redis:
    host: 39.104.97.83
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://172.24.132.96:8761/eureka/
      #defaultZone: http://192.168.23.147:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true

