server:
  port: 31101


spring:
  application:
    name: app-older-opusappraise
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.104.97.83:3306/Pension?serverTimezone=GMT%2B8
    username: kedi
    password: kedi123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.24.132.96:8761/eureka/
      #defaultZone: http://192.168.23.147:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}-hystrix
    prefer-ip-address: true


 