 server:
   port: 31051
 eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true  
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://172.24.132.96:8761/eureka/  
      
 spring:
  application:
    name: app-old-homeservice-r
  datasource:
   url: jdbc:mysql://39.104.97.83/Pension?useUnicode=true&characterEncoding=utf8
   driver-class-name: com.mysql.jdbc.Driver
   username: kedi
   password: kedi123
  logging:
    level: com.kedi.mokuai.dao.OldManMapper=DEBUG
      

 


 