server:
  port: 3062

spring:
  application:
    name: importantnews

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.24.132.96:8761/eureka/
      #defaultZone: http://192.168.23.147:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true

feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能

logging:
  level:
    com.kedi: debug