 server:
   port: 31012
 eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true  
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.23.147:8761/eureka/
      
 spring:
  application:
    name: app-old-elderlyfood-r
  datasource:
   url: jdbc:mysql://39.104.97.83/Pension?useUnicode=true&characterEncoding=utf8
   driver-class-name: com.mysql.jdbc.Driver
   username: kedi
   password: kedi123
   

 


 