server:
  port: 30025

spring:
  application:
    name: home-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://192.168.23.147:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true

