server:
  port: 7001

spring:
  application:
    name: microservice-zuul-gateway

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
    #defaultZone: http://172.24.132.96:8761/eureka/
      #defaultZone: http://192.168.23.147:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true

zuul:
  routes:
    provider-product:
      path: /elderly-health/**
      serviceId: elderly-health
      stripPrefix: true
    provider-order:
      path: /benefit-elderly-wealfare/**
      serviceId: benefit-elderly-wealfare
      stripPrefix: true
    provider-order1:
      path: /evergreen-school/**
      serviceId: evergreen-school
      stripPrefix: true
    provider-order2:
      path: /GoldenRadio/**
      serviceId: GoldenRadio
      stripPrefix: true
    provider-order3:
      path: /head-line/**
      serviceId: head-line
      stripPrefix: true
    provider-order4:
      path: /home-service/**
      serviceId: home-service
      stripPrefix: true
    provider-order5:
      path: /other-source/**
      serviceId: other-source
      stripPrefix: true
    provider-order6:
      path: /bilanshan/**
      serviceId: bilanshan
      stripPrefix: false
    provider-order7:
      path: /news/**
      serviceId: importantnews
      stripPrefix: false